name: Build Android

on:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: armv7
            target: armv7-linux-androideabi

          - name: arm64
            target: aarch64-linux-android

          - name: x86
            target: i686-linux-android

          - name: x86_64
            target: x86_64-linux-android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;27.2.12479018"

      - name: Set Android NDK
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> "$GITHUB_ENV"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> "$GITHUB_ENV"

      - name: Add NDK LLVM to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/bin" >> "$GITHUB_PATH"

      - name: Verify NDK
        run: |
          echo "NDK:"
          echo "$ANDROID_NDK_HOME"

          echo "LLVM:"
          ls "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" \
            | grep -E 'clang$|clang\+\+$'

      - name: Verify target linker
        run: |
          which "${{ matrix.target == 'armv7-linux-androideabi' && 'armv7a-linux-androideabi-clang' || matrix.target == 'aarch64-linux-android' && 'aarch64-linux-android-clang' || matrix.target == 'i686-linux-android' && 'i686-linux-android-clang' || 'x86_64-linux-android-clang' }}"

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Cargo build
        run: |
          cargo build \
            --release \
            --locked \
            --target "${{ matrix.target }}"

      - name: Show output
        run: |
          find "target/${{ matrix.target }}/release" \
            -maxdepth 1 \
            -type f \
            -print
